[package]
name = "caller-utils"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0"
process_macros = "0.1.0"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hyperware_app_common = { git = "https://github.com/hyperware-ai/hyperprocess-macro", rev = "ce0d06e" }
once_cell = "1.20.2"
futures = "0.3"
uuid = { version = "1.0" }
wit-bindgen = "0.41.0"

[lib]
crate-type = ["cdylib", "lib"]
